version: '3'
services:

  project-mongo:
    image: "mongo"
    container_name: project-mongodb
    restart: always
    tty: true
    volumes:
      - project-data:/data/db
    ports:
      - 5432:5432
    networks: 
      - node-network

  project-back:
    hostname: project-back
    build:
      context: project-back
    container_name: project-back
    restart: always
    tty: true
    environment:
      - DB_SERVER=project-mongo
    ports:
      - 20:6000
    links:
      - project-mongo
    networks: 
      - node-network
    command: npm start
    depends_on:
       - project-mongo

  project-front:
    hostname: project-front
    build:
      context: project-front
    container_name: project-front
    restart: always
    tty: true
    ports:
      - 21:5000
    links:
      - project-back
    networks: 
      - node-network
    command: npm start
    depends_on:
       - project-mongo

  nginx:
    build: 
      context: nginx
    container_name: nginx
    restart: always
    tty: true
    ports: 
      - "3000:3000"
    networks: 
      - node-network
    depends_on:
    - project-front
    - project-back

networks: 
  node-network:

volumes:
  project-data: