version: '3'
services:

  project-mongo:
    image: "mongo"
    container_name: project-mongodb
    restart: always
    tty: true
    volumes:
      - project-data:/data/db
    ports:
      - 27018:27017 # Ouverture du port uniquement à des fins de debug/accès sur la machine utilisateur.
    networks: 
      - node-network

  project-back:
    hostname: project-back
    build:
      context: project-back
    container_name: project-back
    restart: always
    tty: true
    environment:
      - DB_SERVER=project-mongo
    ports:
      - 20:6000
    links:
      - project-mongo
    networks: 
      - node-network
    command: npm start
    depends_on:
      - project-mongo
    volumes:
      - project-files:/home/files

  project-front1:
    hostname: project-front1
    build:
      context: project-front
    container_name: project-front1
    restart: always
    tty: true
    ports:
      - 4200:4200
    links:
      - project-back
    networks: 
      - node-network
    command: npm start
    depends_on:
      - project-mongo

  # Front 2 pour le load balancer.
  project-front2:
    hostname: project-front2
    build:
      context: project-front
    container_name: project-front2
    restart: always
    tty: true
    ports:
      - 4201:4200
    links:
      - project-back
    networks: 
      - node-network
    command: npm start
    depends_on:
      - project-mongo

  nginx:
    build: 
      context: nginx
    container_name: nginx
    restart: always
    tty: true
    ports: 
      - "3000:3000"
    networks: 
      - node-network
    depends_on:
    - project-front1
    - project-front2
    - project-back

networks: 
  node-network:

volumes:
  project-data:
  project-files: